// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase configuration
const SUPABASE_URL = "https://hidecvjadhivlyofyovt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZGVjdmphZGhpdmx5b2Z5b3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3MjkyOTAsImV4cCI6MjA4MDMwNTI5MH0.KkDS1ARhR-0BPA5GbQgiWMbjWmEPP-5vzeIy9FT-qVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
